name: CI

on:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: setup go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17

      - name: setup gradle
        uses: gradle/actions/setup-gradle@v4

      - name: install deps
        run: |
          go get .

      - name: start server
        run:
          ./server/gradlew run -p server/server &

      - name: test
        run:
          go test -v ./it
